import { useState, useRef } from 'react';
import { Plus, X, Store, Upload, CheckCircle2, Edit2, Trash2 } from 'lucide-react';

export default function RestaurantSection({ restaurants, onAdd, onUpdate, onDelete }) {
  const [showAdd, setShowAdd] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [form, setForm] = useState({ name: '', menuImage: '', mapImage: '', items: [] });
  const [newItem, setNewItem] = useState({ name: '', price: '' });
  const menuRef = useRef(null);
  const mapRef = useRef(null);
  const handleFile = (e, t) => { const f = e.target.files[0]; if(f) { const r = new FileReader(); r.onloadend = () => setForm(p => ({...p, [t]: r.result })); r.readAsDataURL(f); } };

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-700 font-black">
      <div className="flex justify-between items-center font-black"><h2 className="text-3xl font-black text-stone-800 tracking-tight font-black">식당 라이브러리</h2><button onClick={() => { if(showAdd && isEditing) { setShowAdd(false); setIsEditing(false); setForm({name:'',menuImage:'',mapImage:'',items:[]}); } else setShowAdd(!showAdd); }} className="bg-emerald-600 text-white px-8 py-3.5 rounded-2xl font-black flex items-center gap-2 hover:bg-emerald-700 transition shadow-lg active:scale-95 font-black">{showAdd ? <X size={20}/> : <Plus size={20}/>} {isEditing ? '편집 취소' : showAdd ? '닫기' : '식당 추가'}</button></div>
      {showAdd && (<div className="bg-white p-10 rounded-[2.5rem] shadow-xl border border-stone-100 space-y-8 animate-in slide-in-from-top-4 shadow-stone-200/50 font-black"><div className="grid grid-cols-1 md:grid-cols-3 gap-8 font-black"><div className="space-y-1.5 font-black"><label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1 font-black">식당 명칭</label><input className="w-full bg-stone-50 border-none rounded-2xl p-5 focus:ring-2 focus:ring-emerald-500 transition shadow-inner font-bold font-black" placeholder="예: 소담 한정식" value={form.name} onChange={e => setForm({...form, name: e.target.value})} /></div><div className="space-y-1.5 font-black"><label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1 font-black">메뉴판 파일</label><div onClick={() => menuRef.current.click()} className="bg-stone-50 border-2 border-dashed border-stone-200 rounded-2xl p-5 flex items-center justify-center cursor-pointer hover:border-emerald-300 transition shadow-inner font-bold text-stone-400 text-xs font-black">{form.menuImage ? <CheckCircle2 className="text-emerald-500 font-black" /> : <Upload size={18}/>}<span className="ml-2 font-black">{form.menuImage ? '업로드 완료' : '파일 선택'}</span><input type="file" ref={menuRef} className="hidden font-black" onChange={e => handleFile(e, 'menuImage')} /></div></div><div className="space-y-1.5 font-black"><label className="text-[10px] font-black text-stone-400 uppercase tracking-widest px-1 font-black">약도 파일</label><div onClick={() => mapRef.current.click()} className="bg-stone-50 border-2 border-dashed border-stone-200 rounded-2xl p-5 flex items-center justify-center cursor-pointer hover:border-emerald-300 transition shadow-inner font-bold text-stone-400 text-xs font-black">{form.mapImage ? <CheckCircle2 className="text-emerald-500 font-black" /> : <Upload size={18}/>}<span className="ml-2 font-black">{form.mapImage ? '업로드 완료' : '파일 선택'}</span><input type="file" ref={mapRef} className="hidden font-black" onChange={e => handleFile(e, 'mapImage')} /></div></div></div>
        <div className="bg-stone-50 p-8 rounded-[2rem] border border-stone-100 shadow-inner font-black"><div className="flex gap-4 mb-6 font-black"><input className="flex-1 bg-white border-none rounded-2xl p-4 text-sm shadow-sm font-black" placeholder="메뉴 이름" value={newItem.name} onChange={e => setNewItem({...newItem, name: e.target.value})} /><input className="w-32 bg-white border-none rounded-2xl p-4 text-sm shadow-sm font-black" placeholder="가격(원)" type="number" value={newItem.price} onChange={e => setNewItem({...newItem, price: e.target.value === '' ? '' : parseInt(e.target.value)})} /><button onClick={() => { if(newItem.name && newItem.price) { setForm({...form, items: [...form.items, {...newItem, id: Date.now()}]}); setNewItem({name:'',price:''}); } }} className="bg-stone-800 text-white px-8 rounded-2xl font-black active:scale-95 transition shadow-lg hover:bg-black font-black">추가</button></div><div className="flex flex-wrap gap-2.5 font-black">{form.items.map(item => <span key={item.id} className="bg-white px-4 py-2.5 rounded-xl border text-xs font-black flex items-center gap-3 shadow-sm border-stone-100 font-black">{item.name} <span className="text-emerald-600 font-black">{item.price.toLocaleString()}원</span><button onClick={() => setForm({...form, items: form.items.filter(i => i.id !== item.id)})} className="text-stone-300 hover:text-red-500 transition-colors font-black"><X size={16}/></button></span>)}</div></div>
        <button className="w-full bg-stone-900 text-white py-6 rounded-[1.8rem] font-black text-xl hover:bg-emerald-600 transition shadow-2xl active:scale-95 shadow-stone-900/20 font-black" onClick={() => { if(isEditing) onUpdate(form); else onAdd(form); setShowAdd(false); setIsEditing(false); setForm({name:'',menuImage:'',mapImage:'',items:[]}); }}>정보 저장하기</button></div>)}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 font-black">{restaurants.map(rest => (<div key={rest.id} className="bg-white rounded-[3rem] overflow-hidden border border-stone-100 shadow-sm hover:shadow-2xl transition-all duration-700 group relative shadow-stone-200/50 font-black"><div className="absolute top-8 right-8 z-20 flex gap-2.5 shadow-2xl rounded-2xl font-black"><button onClick={() => {setForm(rest); setIsEditing(true); setShowAdd(true); scrollToTop();}} className="p-4 bg-white/90 rounded-2xl opacity-0 group-hover:opacity-100 hover:bg-emerald-500 hover:text-white transition shadow-lg font-black"><Edit2 size={18} className="font-black"/></button><button onClick={() => onDelete(rest.id)} className="p-4 bg-white/90 rounded-2xl opacity-0 group-hover:opacity-100 hover:bg-red-500 hover:text-white transition shadow-lg font-black"><Trash2 size={18} className="font-black"/></button></div><div className="relative h-72 overflow-hidden bg-stone-100 font-black">{rest.menuImage ? <img src={rest.menuImage} className="w-full h-full object-cover group-hover:scale-110 transition duration-1000 font-black" alt={rest.name} /> : <div className="w-full h-full flex items-center justify-center text-stone-200 uppercase tracking-widest font-black text-xs font-black">No Visual Data</div>}<div className="absolute inset-0 bg-gradient-to-t from-stone-900/90 via-stone-900/20 to-transparent flex flex-col justify-end p-10 text-white shadow-inner font-black"><h3 className="text-2xl font-black tracking-tight font-black">{rest.name}</h3><p className="text-[11px] font-bold text-stone-300 mt-2 uppercase tracking-widest flex items-center gap-2 opacity-80 font-black font-black"><Store size={12}/> {rest.items.length} Menu Items Available</p></div></div></div>))}</div>
    </div>
  );
}
